/*
 * @Descripttion: pangoo-dm
 * @version: 1.0
 * @Author: uidq1343
 * @Date: 2022-03-08 17:35:13
 * @LastEditors: uidq1343
 * @LastEditTime: 2022-03-25 14:58:39
 * @content: edit your page content
 */
import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit'
import { fetching, Fetching } from '../../common/interface'
import Axios from '../../common/axios/axios'
import { getErrorMsg } from '../../common/utils/reduxUtil'
export interface DominationState extends Fetching {
    favourite: any[];
    hot: any[];
    recommend: any[];
    trending: any[];
}

const initialState: DominationState = {
    ...fetching,
    loading: false,
    favourite: [],
    hot: [],
    recommend: [],
    trending: []
}
// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const exploreDataSetAction = createAsyncThunk(
    'dataSet/explore',
    async (params, { rejectWithValue }) => {
        try {
            // throw new Error('Something bad happened');
            const response = await Axios.get(`/api/pangoo-data-set/dataSet/explore`)
            return response.data;
        } catch (err) {
            return rejectWithValue(err)
        }
    }
);

export const exploreSlice = createSlice({
    name: 'domination',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
        // increment: (state) => {
        //     state.value += 1;
        // },
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
            .addCase(exploreDataSetAction.pending, (state) => {
                state.loading = true
            })
            .addCase(exploreDataSetAction.rejected, (state, action) => {
                state.loadError = true
                state.loading = false

                state.errorMsg = getErrorMsg(action)
            })
            .addCase(exploreDataSetAction.fulfilled, (state, action) => {
                state.loading = false
                state.favourite = action.payload.data.favourite
                state.hot = action.payload.data.hot
                state.recommend = action.payload.data.recommend
                state.trending = action.payload.data.trending
            });
    },
});

// export const { increment, decrement, incrementByAmount } = exploreSlice.actions;
export default exploreSlice.reducer;
