/*
 * @Descripttion: pangoo-dm
 * @version: 1.0
 * @Author: uidq1343
 * @Date: 2022-02-14 10:54:00
 * @LastEditors: uidq1343
 * @LastEditTime: 2022-03-22 13:41:32
 * @content: edit your page content
 */
import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit'
import { fetching, Fetching } from '../../common/interface'
import Axios from '../../common/axios/axios'
import { getErrorMsg } from '../../common/utils/reduxUtil'



const initialState = {
    ...fetching,
    loading: false,
    isSuccess: false,
    dataSet:null,
    taskInfo:null,

}
// The function below is called a thunk and allows us to perform async logic. It
// can be dispatched like a regular action: `dispatch(incrementAsync(10))`. This
// will call the thunk with the `dispatch` function as the first argument. Async
// code can then be executed and other actions can be dispatched. Thunks are
// typically used to make async requests.
export const uploadFileAction = createAsyncThunk(
    'dataSet/uploadFile',
    async (params, { rejectWithValue }) => {
        try {
            const response = await Axios.patch(`/api/pangoo-data-set/dataSet/file/tree/local/upload?dataSetId=${params.dataSetId}&isUnzip=${params.isUnzip}&parentFolderId=${params.parentFolderId}`)
            return response.data;
        } catch (err) {
            return rejectWithValue(err)
        }
    }
);






export const uploadFileSlice = createSlice({
    name: 'uploadFile',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
    extraReducers: (builder) => {
        builder
           
            .addCase(uploadFileAction.pending, (state) => {
                state.loading = true
                state.loadError = false
                state.errorMsg = ""
                state.isSuccess = false
            })
            .addCase(uploadFileAction.rejected, (state, action) => {
                state.loadError = true
                state.loading = false
                state.errorMsg = getErrorMsg(action)
            })
            .addCase(uploadFileAction.fulfilled, (state, action) => {
                state.loading = false
                state.isSuccess = true
            })


    },
});

// export const { increment, decrement, incrementByAmount } = exploreSlice.actions;
export default uploadFileSlice.reducer;
