const EVENT_DEALING_MATCH = 'EVENT_DEALING_MATCH'
const EVENT_USER_ID = 'EVENT_USER_ID'
const REFRESH_INTERVAL_FAST = 2000
const REFRESH_INTERVAL_SLOW = 5000
export default {
  EVENT_DEALING_MATCH,
  EVENT_USER_ID,
  REFRESH_INTERVAL_FAST,
  REFRESH_INTERVAL_SLOW
}
