/*
 * @Descripttion: pangoo-dm
 * @version: 1.0
 * @Author: uidq1343
 * @Date: 2021-12-01 15:52:33
 * @LastEditors: uidq1343
 * @LastEditTime: 2022-05-07 13:40:31
 * @content: edit your page content
 */



export enum UserActionTypes {
    GET_USERS = 'GET_USERS',
    GET_USERS_SUCCESS = 'GET_USERS_SUCCESS',
    USERS_ERROR = 'USERS_ERROR',

    DIRECT_TO_DOMINATION = 'DIRECT_TO_DOMINATION',
    DIRECT_DOWN = 'DIRECT_DOWN',
    LOG_OUT = 'LOG_OUT',

    GET_PUBLIC_KEY = 'GET_PUBLIC_KEY',
    GET_PUBLIC_KEY_SUCCESS = 'GET_PUBLIC_KEY_SUCCESS',
    GET_PUBLIC_KEY_ERROR = 'GET_PUBLIC_KEY_ERROR',


    APPLY_PERMISSION='APPLY_PERMISSION',
    APPLY_PERMISSION_SUCCESS='APPLY_PERMISSION_SUCCESS',
    APPLY_PERMISSION_ERROR='APPLY_PERMISSION_ERROR',

    GET_APPLY_PERMISSION_LIST='GET_APPLY_PERMISSION_LIST',
    GET_APPLY_PERMISSION_LIST_SUCCESS='GET_APPLY_PERMISSION_LIST_SUCCESS',
    GET_APPLY_PERMISSION_LIST_ERROR='GET_APPLY_PERMISSION_LIST_ERROR',


    APPLY_PERMISSION_OPERATE='APPLY_PERMISSION_OPERATE',
    APPLY_PERMISSION_OPERATE_SUCCESS='APPLY_PERMISSION_OPERATE_SUCCESS',
    APPLY_PERMISSION_OPERATE_ERROR='APPLY_PERMISSION_OPERATE_ERROR',
}

export enum DatasetExploreActionType {
    GET_CLASSES = 'GET_CLASSES',
    GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS',
    GET_CLASSES_ERROR = 'GET_CLASSES_ERROR',
    GET_HOLE_DATASET = 'GET_HOLE_DATASET',
    GET_HOLE_DATASET_SUCCESS = 'GET_HOLE_DATASET_SUCCESS',
    GET_HOLE_DATASET_ERROR = 'GET_HOLE_DATASET_ERROR',
    GET_SINGLE_DATASET = 'GET_SINGLE_DATASET',
    GET_SINGLE_DATASET_SUCCESS = 'GET_SINGLE_DATASET_SUCCESS',
    GET_SINGLE_DATASET_ERROR = 'GET_SINGLE_DATASET_ERROR',

    POST_FAVORATE_DATASET = 'POST_FAVORATE_DATASET',
    POST_FAVORATE_DATASET_SUCCESS = 'POST_FAVORATE_DATASET_SUCCESS',
    POST_FAVORATE_DATASET_ERROR = 'POST_FAVORATE_DATASET_ERROR',


    
}


//数据集创建，数据集文件浏览
export enum InSensitiveActionType {
    GET_DATA_DICTIONARY = 'GET_DATA_DICTIONARY',
    GET_DATA_DICTIONARY_SUCCESS = 'GET_DATA_DICTIONARY_SUCCESS',
    GET_DATA_DICTIONARY_ERROR = 'GET_DATA_DICTIONARY_ERROR',

    CREATE_DATASET = 'CREATE_DATASET',
    CREATE_DATASET_SUCCESS = 'CREATE_DATASET_SUCCESS',
    CREATE_DATASET_ERROR = 'CREATE_DATASET_ERROR',



    GET_CREATE_DATASET_STATUS = 'GET_CREATE_DATASET_STATUS',
    GET_CREATE_DATASET_STATUS_SUCCESS = 'GET_CREATE_DATASET_STATUS_SUCCESS',
    GET_CREATE_DATASET_STATUS_ERROR = 'GET_CREATE_DATASET_STATUS_ERROR',


    UPLOAD_DATASET_FILES = 'UPLOAD_DATASET_FILES',
    UPLOAD_DATASET_FILES_SUCCESS = 'UPLOAD_DATASET_FILES_SUCCESS',
    UPLOAD_DATASET_FILES_ERROR = 'UPLOAD_DATASET_FILES_ERROR',



    DELETE_DATASET = 'DELETE_DATASET',
    DELETE_DATASET_SUCCESS = 'DELETE_DATASET_SUCCESS',
    DELETE_DATASET_ERROR = 'DELETE_DATASET_ERROR',

    
    GET_DATASET_FOLDER_LIST = 'GET_DATASET_FOLDER_LIST',
    GET_DATASET_FOLDER_LIST_SUCCESS = 'GET_DATASET_FOLDER_LIST_SUCCESS',
    GET_DATASET_FOLDER_LIST_ERROR = 'GET_DATASET_FOLDER_LIST_ERROR',

    UPDATE_DATASET_FOLDER_LIST = 'UPDATE_DATASET_FOLDER_LIST',
    UPDATE_DATASET_FOLDER_LIST_SUCCESS = 'UPDATE_DATASET_FOLDER_LIST_SUCCESS',
    UPDATE_DATASET_FOLDER_LIST_ERROR = 'UPDATE_DATASET_FOLDER_LIST_ERROR',

    DATASET_FOLDER_FILE_TREE_TOGGLE = 'DATASET_FOLDER_FILE_TREE_TOGGLE',

    DATASET_SELECT_FOLDER_TOGGLE = 'DATASET_SELECT_FOLDER_TOGGLE',
    DATASET_SELECT_FOLDER_TOGGLE_SUCCESS = 'DATASET_SELECT_FOLDER_TOGGLE_SUCCESS',
    DATASET_SELECT_FOLDER_TOGGLE_ERROR = 'DATASET_SELECT_FOLDER_TOGGLE_ERROR',

    DATASET_SELECT_FOLDER_CLEAR = 'DATASET_SELECT_FOLDER_CLEAR',


    DATASET_SELECT_FILE_VIEW = 'DATASET_SELECT_FILE_VIEW',

    DELETE_DATASET_FOLDER_LIST = 'DELETE_DATASET_FOLDER_LIST',
    DELETE_DATASET_FOLDER_LIST_SUCCESS = 'DELETE_DATASET_FOLDER_LIST_SUCCESS',
    DELETE_DATASET_FOLDER_LIST_ERROR = 'DELETE_DATASET_FOLDER_LIST_ERROR',

    GET_SELECT_FOLER_PATH = 'GET_SELECT_FOLER_PATH',
    GET_SELECT_FOLER_PATH_SUCCESS = 'GET_SELECT_FOLER_PATH_SUCCESS',
    GET_SELECT_FOLER_PATHT_ERROR = 'GET_SELECT_FOLER_PATHT_ERROR',

    ADD_IDS_FILES_TO_DATASET = 'ADD_IDS_FILES_TO_DATASET',
    ADD_IDS_FILES_TO_DATASET_SUCCESS = 'ADD_IDS_FILES_TO_DATASET_SUCCESS',
    ADD_IDS_FILES_TO_DATASET_ERROR = 'ADD_IDS_FILES_TO_DATASET_ERROR',

    SUBMIT_DATASET_FILES = 'SUBMIT_DATASET_FILES',
    SUBMIT_DATASET_FILES_SUCCESS = 'SUBMIT_DATASET_FILES_SUCCESS',
    SUBMIT_DATASET_FILES_ERROR = 'SUBMIT_DATASET_FILES_ERROR',

    CLEAR_DATASET_FILES_CACHE = 'CLEAR_DATASET_FILES_CACHE',


    GET_ROOT_PATH = 'GET_ROOT_PATH',
    GET_ROOT_PATH_SUCCESS = 'GET_ROOT_PATH_SUCCESS',
    GET_ROOT_PATH_ERROR = 'GET_ROOT_PATH_ERROR',

    GET_PROJECT_LIST = 'GET_SEARCH_DISTINATION_PROJECT_LIST',
    GET_PROJECT_LIST_SUCCESS = 'GET_SEARCH_DISTINATION_PROJECT_LIST_SUCCESS',
    GET_PROJECT_LIST_ERROR = 'GET_SEARCH_DISTINATION_PROJECT_LIST_ERROR',
    



    CREATE_INSENSITIVE_FOLDER = 'CREATE_INSENSITIVE_FOLDER',
    CREATE_INSENSITIVE_FOLDER_SUCCESS = 'CREATE_INSENSITIVE_FOLDER_SUCCESS',
    CREATE_INSENSITIVE_FOLDER_ERROR = 'CREATE_INSENSITIVE_FOLDER_ERROR',


    DELETE_INSENSITIVE_FOLDER = 'DELETE_INSENSITIVE_FOLDER',
    DELETE_INSENSITIVE_FOLDER_SUCCESS = 'DELETE_INSENSITIVE_FOLDER_SUCCESS',
    DELETE_INSENSITIVE_FOLDER_ERROR = 'DELETE_INSENSITIVE_FOLDER_ERROR',



    
    GET_SEARCH_MOVE_TASK = 'GET_SEARCH_MOVE_TASK',
    GET_SEARCH_MOVE_TASK_SUCCESS = 'GET_SEARCH_MOVE_TASK_SUCCESS',
    GET_SEARCH_MOVE_TASK_ERROR = 'GET_SEARCH_MOVE_TASK_ERROR',
    
    DELETE_SEARCH_MOVE_TASK = 'DELETE_SEARCH_MOVE_TASK',
    DELETE_SEARCH_MOVE_TASK_SUCCESS = 'DELETE_SEARCH_MOVE_TASK_SUCCESS',
    DELETE_SEARCH_MOVE_TASK_ERROR = 'DELETE_SEARCH_MOVE_TASK_ERROR',
}


//IDS文件搜索浏览
export enum FilesAndFoldersActionType {

    GET_PROJECT_LIST = 'GET_PROJECT_LIST',
    GET_PROJECT_LIST_SUCCESS = 'GET_PROJECT_LIST_SUCCESS',
    GET_PROJECT_LIST_ERROR = 'GET_PROJECT_LIST_ERROR',


    GET_LABELS_STATISTIC = 'GET_LABELS_STATISTIC',
    GET_LABELS_STATISTIC_SUCCESS = 'GET_LABELS_STATISTIC_SUCCESS',
    GET_LABELS_STATISTIC_ERROR = 'GET_LABELS_STATISTIC_ERROR',
    



    GET_SELECT_FOLDER_CONTENT_LIST = 'GET_SELECT_FOLDER_CONTENT_LIST',
    GET_SELECT_FOLDER_CONTENT_LIST_SUCCESS = 'GET_SELECT_FOLDER_CONTENT_LIST_SUCCESS',
    GET_SELECT_FOLDER_CONTENT_LIST_ERROR = 'GET_SELECT_FOLDER_CONTENT_LIST_ERROR',
    FOLDER_FILE_TREE_TOGGLE = 'FOLDER_FILE_TREE_TOGGLE',


    GET_ROOT_PATH = 'GET_ROOT_PATH',
    GET_ROOT_PATH_SUCCESS = 'GET_ROOT_PATH_SUCCESS',
    GET_ROOT_PATH_ERROR = 'GET_ROOT_PATH_ERROR',
    
    
    SEARCH_ACTIVE = 'SEARCH_ACTIVE',
    SEARCH_DEACTIVE = 'SEARCH_DEACTIVE',

    FILE_NODE_SELECTED='FILE_NODE_SELECTED',


    UPDATE_SEARCH_WITH_PARAMS = 'UPDATE_SEARCH_WITH_PARAMS',

    SEARCH_WITH_PARAMS = 'SEARCH_WITH_PARAMS',
    SEARCH_WITH_PARAMS_SUCCESS = 'SEARCH_WITH_PARAMS_SUCCESS',
    SEARCH_WITH_PARAMS_ERROR = 'SEARCH_WITH_PARAMS_ERROR',

    
    FILESANDFOLDERS_TOTAL = 'FILESANDFOLDERS_TOTAL',
    FILESANDFOLDERS_TOTAL_SUCCESS = 'FILESANDFOLDERS_TOTAL_SUCCESS',
    FILESANDFOLDERS_TOTAL_ERROR = 'FILESANDFOLDERS_TOTAL_ERROR',


    EXPLORE_MODE_UPDATE = 'EXPLORE_MODE_UPDATE',




    MERGE_ACTIVE = 'MERGE_ACTIVE',
    MERGE_DEACTIVE = 'MERGE_DEACTIVE',

    MERGE_INDEX='MERGE_INDEX',
    MERGE_INDEX_SUCCESS='MERGE_INDEX_SUCCESS',
    MERGE_INDEX_ERROR='MERGE_INDEX_ERROR',



    LABEL_POINT_ARRAYS='LABEL_POINT_ARRAYS',
    LABEL_POINT_ARRAYS_FILTER='LABEL_POINT_ARRAYS_FILTER',
    LABEL_POINT_ARRAYS_FILTER_CLEAR='LABEL_POINT_ARRAYS_FILTER_CLEAR',




    SEARCH_AND_MOVE_WITH_PARAMS = 'SEARCH_AND_MOVE_WITH_PARAMS',
    SEARCH_AND_MOVE_WITH_PARAMS_SUCCESS = 'SEARCH_AND_MOVE_WITH_PARAMS_SUCCESS',
    SEARCH_AND_MOVE_WITH_PARAMS_ERROR = 'SEARCH_AND_MOVE_WITH_PARAMS_ERROR',


}